package com.ainosoft.seleniumplacescraper.pojo;

// default package
// Generated 10 May, 2016 2:56:52 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SpaceInformation generated by hbm2java
 */
@Entity
@Table(name = "space_information", catalog = "SeleniumPlacesScraper")
public class SpaceInformationPojo implements java.io.Serializable {

	private Long id;
	private String spaceType;
	private String spaceCity;
	private Integer pageCount;

	public SpaceInformationPojo() {
	}

	public SpaceInformationPojo(String spaceType, String spaceCity,
			Integer pageCount) {
		this.spaceType = spaceType;
		this.spaceCity = spaceCity;
		this.pageCount = pageCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "space_type", length = 100)
	public String getSpaceType() {
		return this.spaceType;
	}

	public void setSpaceType(String spaceType) {
		this.spaceType = spaceType;
	}

	@Column(name = "space_city", length = 100)
	public String getSpaceCity() {
		return this.spaceCity;
	}

	public void setSpaceCity(String spaceCity) {
		this.spaceCity = spaceCity;
	}

	@Column(name = "page_count")
	public Integer getPageCount() {
		return this.pageCount;
	}

	public void setPageCount(Integer pageCount) {
		this.pageCount = pageCount;
	}

}
